apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: rudderstack
subjects:
- kind: ServiceAccount
  name: default
  namespace: rudderstack
roleRef:
  kind: Role
  name: reader
  apiGroup: rbac.authorization.k8s.io
