apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: rudderstack
  name: reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "patch"]